CREATE TABLE PROFILE (
	PID INTEGER NOT NULL AUTO_INCREMENT,
	Email varchar(100) NOT NULL,
	Phone varchar(12),
	Fname varchar(100) NOT NULL,
	Lname varchar(100) NOT NULL,
	Minit CHAR,
	Jdate DateTime NOT NULL,
	P_TYPE CHAR NOT NULL,
	P_Password varchar(12) NOT NULL,
	Uname varchar(12) NOT NULL UNIQUE,
	Ssn varchar(9),
	UNIQUE(PID),
	UNIQUE(Email),
	UNIQUE(Phone),
	UNIQUE(Uname),
	PRIMARY KEY (PID)
);

CREATE TABLE ANIMAL(
	AID INTEGER NOT NULL AUTO_INCREMENT,
	Added_by INTEGER NOT NULL,
	Removed_by INTEGER DEFAULT NULL,
	Name varchar(100),
	A_TYPE CHAR NOT NULL,
	Sex CHAR NOT NULL,
	Color varchar(50) NOT NULL,
	Diet varchar(200),
	Available BIT NOT NULL,
	Weight FLOAT NOT NULL,
	Height FLOAT NOT NULL,
	DoB DateTime NOT NULL,
	is_kid_friendly BIT NOT NULL,
	is_vac BIT,
	Description varchar(500),
	A_date DateTime NOT NULL,
	Breed varchar(20),
	UNIQUE(AID),
	PRIMARY KEY(AID),
	FOREIGN KEY (Added_by) REFERENCES PROFILE(PID) ON DELETE NO ACTION ON UPDATE CASCADE,
	FOREIGN KEY (Removed_by) REFERENCES PROFILE(PID) ON DELETE NO ACTION ON UPDATE CASCADE
);
CREATE TABLE LIKES(
	AID INTEGER NOT NULL,
	PID INTEGER NOT NULL,
	FOREIGN KEY (AID) REFERENCES ANIMAL(AID),
	FOREIGN KEY (PID) REFERENCES PROFILE(PID),
	PRIMARY KEY (AID, PID)
);

CREATE TABLE DONATES_TO(
	d_id INTEGER NOT NULL AUTO_INCREMENT,
	AID INTEGER NOT NULL,
	PID INTEGER NOT NULL,
	Amount float NOT NULL,
	D_date DateTime NOT NULL,
	UNIQUE(d_id),
	FOREIGN KEY (AID) REFERENCES ANIMAL(AID),
	FOREIGN KEY (PID) REFERENCES PROFILE(PID),
	PRIMARY KEY (d_id)
);

CREATE TABLE A_sickness(
	AID INTEGER NOT NULL,
	Sickness_str varchar(50),
	FOREIGN KEY (AID) REFERENCES ANIMAL(AID) ON DELETE CASCADE,
	PRIMARY KEY (AID, Sickness_str)
);

CREATE TABLE ANSWERS(
	admin_id INTEGER NOT NULL,
	a_date DateTime NOT NULL,
	a_ans VARCHAR(500) NOT NULL,
	FOREIGN KEY (admin_id) REFERENCES PROFILE(PID),
	PRIMARY KEY(admin_id, a_date)
);

CREATE TABLE INQUIRY(
	U_PID INTEGER NOT NULL,
	A_PID INTEGER DEFAULT NULL,
	AID INTEGER NOT NULL,
	u_date DateTime NOT NULL,
	u_q varchar(500),
	a_date DateTime,
	FOREIGN KEY (AID) REFERENCES ANIMAL(AID),
	FOREIGN KEY (U_PID) REFERENCES PROFILE(PID),
	FOREIGN KEY (A_PID) REFERENCES PROFILE(PID),
	PRIMARY KEY (U_PID, AID, u_date)
);

CREATE TABLE INSECT(
	AID INTEGER NOT NULL,
	is_Poison BIT NOT NULL,
	has_Wings BIT NOT NULL,
	FOREIGN KEY (AID) REFERENCES ANIMAL(AID) ON DELETE CASCADE,
	PRIMARY KEY (AID)
);

CREATE TABLE BIRD(
	AID INTEGER NOT NULL,
	w_span FLOAT NOT NULL,
	isNoisy BIT NOT NULL,
	FOREIGN KEY (AID) REFERENCES ANIMAL(AID) ON DELETE CASCADE,
	PRIMARY KEY (AID)
);

CREATE TABLE SNAKE(
	AID INTEGER NOT NULL,
	is_Poison BIT NOT NULL,
	s_Length FLOAT NOT NULL,
	FOREIGN KEY (AID) REFERENCES ANIMAL(AID) ON DELETE CASCADE,
	PRIMARY KEY (AID)
);

CREATE TABLE CAT(
	AID INTEGER NOT NULL,
	isDeclaw BIT NOT NULL,
	canReproduce BIT NOT NULL,
	FOREIGN KEY (AID) REFERENCES ANIMAL(AID) ON DELETE CASCADE,
	PRIMARY KEY (AID)
);

CREATE TABLE FISH(
	AID INTEGER NOT NULL,
	w_type CHAR NOT NULL,
	Tanksize INTEGER NOT NULL,
	FOREIGN KEY (AID) REFERENCES ANIMAL(AID) ON DELETE CASCADE,
	PRIMARY KEY (AID)
);

CREATE TABLE HORSE(
	AID INTEGER NOT NULL,
	isRide BIT NOT NULL,
	Speed INTEGER NOT NULL,
	FOREIGN KEY (AID) REFERENCES ANIMAL(AID) ON DELETE CASCADE,
	PRIMARY KEY (AID)
);

CREATE TABLE DOG(
	AID INTEGER NOT NULL,
	canReproduce BIT NOT NULL,
	FOREIGN KEY (AID) REFERENCES ANIMAL(AID) ON DELETE CASCADE,
	PRIMARY KEY (AID)
);
